import React, { useEffect, useState } from "react";
import Link from "next/link";
import Head from "next/head";
import Image from "next/image";
import {
  HomeMain,
  HomeFooter,
  HomeContainer,
  HomeHeader,
  ReturnArrow,
} from "styles/pagesStyles/Home.styles";
import BookDetails from "src/components/BookDetails";
import backArrow from "public/arrow.png";

export default function ItemDetails() {
  return (
    <HomeContainer>
      <Head>
        <title>Zeelo app</title>
        <meta
          name="app requested by zeelo"
          content="Generated by Ángel Bernardo Lupiáñez"
        />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <HomeHeader>Header</HomeHeader>
      <ReturnArrow>
        <Link
          href={{
            pathname: "/ItemsList",
          }}
          passHref
        >
          <div>
            <Image src={backArrow} alt="back arrow" width={50} height={50} />
          </div>
        </Link>
      </ReturnArrow>
      <HomeMain>
        <BookDetails />
      </HomeMain>

      <HomeFooter>
        <div>
          Made by <br /> Ángel Bernardo Lupiáñez
        </div>
        <div>Powered by React</div>
      </HomeFooter>
    </HomeContainer>
  );
}
