import React from "react";
import Head from "next/head";

import {
  HomeMain,
  HomeFooter,
  HomeContainer,
  HomeHeader,
} from "styles/pagesStyles/Home.styles";
import BookList from "src/components/BookList";
import CustomHeader from "src/CustomHeader";

const Home: React.FC = () => {
  return (
    <HomeContainer>
      <Head>
        <title>Library app</title>
        <meta
          name="Library App"
          content="Generated by Ángel Bernardo Lupiáñez"
        />
        <link rel="icon" href="/favi.ico" />
      </Head>
      <HomeHeader>
        <CustomHeader />
      </HomeHeader>
      <HomeMain>
        <BookList />
      </HomeMain>

      <HomeFooter>
        <div>
          Made by <br /> Ángel Bernardo Lupiáñez
        </div>
        <div>Powered by React</div>
      </HomeFooter>
    </HomeContainer>
  );
};

export default Home;
