import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { HomeMain, HomeFooter,HomeContainer,HomeHeader } from "../styles/pagesStyles/Home.styles";

export default function Home() {
  return (
    <HomeContainer>
      <Head>
        <title>Zeelo app</title>
        <meta
          name="app requested by zeelo"
          content="Generated by Ángel Bernardo Lupiáñez"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeHeader>Header</HomeHeader>
      <HomeMain>Hello world</HomeMain>

      <HomeFooter>
        Made by <br /> Ángel Bernardo Lupiáñez
      </HomeFooter>
    </HomeContainer>
  );
}
